//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtcWalletUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BtcWalletUI.Resources.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address and Amount needed for Calculation.
        /// </summary>
        internal static string AddressAndAmountNeededForCalculation {
            get {
                return ResourceManager.GetString("AddressAndAmountNeededForCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Selected Fee.
        /// </summary>
        internal static string AutomaticallySelectedFee {
            get {
                return ResourceManager.GetString("AutomaticallySelectedFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Selected Gas Limit.
        /// </summary>
        internal static string AutomaticallySelectedGasLimit {
            get {
                return ResourceManager.GetString("AutomaticallySelectedGasLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Selected Gas Price.
        /// </summary>
        internal static string AutomaticallySelectedGasPrice {
            get {
                return ResourceManager.GetString("AutomaticallySelectedGasPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ᐸ.
        /// </summary>
        internal static string BackArrow {
            get {
                return ResourceManager.GetString("BackArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTC.
        /// </summary>
        internal static string BTC {
            get {
                return ResourceManager.GetString("BTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTC Wallet.
        /// </summary>
        internal static string BTCWallet {
            get {
                return ResourceManager.GetString("BTCWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Sending Account.
        /// </summary>
        internal static string ChooseSendingAccount {
            get {
                return ResourceManager.GetString("ChooseSendingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmations.
        /// </summary>
        internal static string Confirmations {
            get {
                return ResourceManager.GetString("Confirmations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Status.
        /// </summary>
        internal static string ConfirmationStatus {
            get {
                return ResourceManager.GetString("ConfirmationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Address.
        /// </summary>
        internal static string ContractAddress {
            get {
                return ResourceManager.GetString("ContractAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy To Clipboard.
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto Wallet.
        /// </summary>
        internal static string CryptoWallet {
            get {
                return ResourceManager.GetString("CryptoWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Details for Transaction.
        /// </summary>
        internal static string EnterDetailsForTransaction {
            get {
                return ResourceManager.GetString("EnterDetailsForTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addTransaction.
        /// </summary>
        internal static string ERC20PageMethodAddTx {
            get {
                return ResourceManager.GetString("ERC20PageMethodAddTx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removeTransaction.
        /// </summary>
        internal static string ERC20PageMethodRemoveTx {
            get {
                return ResourceManager.GetString("ERC20PageMethodRemoveTx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updateBalance.
        /// </summary>
        internal static string ERC20PageMethodUpdateBalance {
            get {
                return ResourceManager.GetString("ERC20PageMethodUpdateBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updateTransaction.
        /// </summary>
        internal static string ERC20PageMethodUpdateTx {
            get {
                return ResourceManager.GetString("ERC20PageMethodUpdateTx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERC20 Wallet.
        /// </summary>
        internal static string ERC20Wallet {
            get {
                return ResourceManager.GetString("ERC20Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETH.
        /// </summary>
        internal static string ETH {
            get {
                return ResourceManager.GetString("ETH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETH Wallet.
        /// </summary>
        internal static string ETHWallet {
            get {
                return ResourceManager.GetString("ETHWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        internal static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.
        /// </summary>
        internal static string Gas {
            get {
                return ResourceManager.GetString("Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas Limit.
        /// </summary>
        internal static string GasLimit {
            get {
                return ResourceManager.GetString("GasLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas Price.
        /// </summary>
        internal static string GasPrice {
            get {
                return ResourceManager.GetString("GasPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get New Address.
        /// </summary>
        internal static string GenerateNewAddress {
            get {
                return ResourceManager.GetString("GenerateNewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are fetching transactions, Balance will be updated after all transactions are fetched, please wait..
        /// </summary>
        internal static string GettingTransactionsMsg {
            get {
                return ResourceManager.GetString("GettingTransactionsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gwei.
        /// </summary>
        internal static string Gwei {
            get {
                return ResourceManager.GetString("Gwei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash.
        /// </summary>
        internal static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs.
        /// </summary>
        internal static string Inputs {
            get {
                return ResourceManager.GetString("Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Coin Selection Mode.
        /// </summary>
        internal static string ManualCoinSelectionMode {
            get {
                return ResourceManager.GetString("ManualCoinSelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Fee Selection Mode.
        /// </summary>
        internal static string ManualFeeSelectionMode {
            get {
                return ResourceManager.GetString("ManualFeeSelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Gas Limit Selection Mode.
        /// </summary>
        internal static string ManualGasLimitSelectionMode {
            get {
                return ResourceManager.GetString("ManualGasLimitSelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Gas Price Selection Mode.
        /// </summary>
        internal static string ManualGasPriceSelectionMode {
            get {
                return ResourceManager.GetString("ManualGasPriceSelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFT.
        /// </summary>
        internal static string NFT {
            get {
                return ResourceManager.GetString("NFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFT Assets.
        /// </summary>
        internal static string NftAssets {
            get {
                return ResourceManager.GetString("NftAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        internal static string Outputs {
            get {
                return ResourceManager.GetString("Outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive BTC.
        /// </summary>
        internal static string ReceiveBtc {
            get {
                return ResourceManager.GetString("ReceiveBtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive BTC ↓.
        /// </summary>
        internal static string ReceiveBtcArrow {
            get {
                return ResourceManager.GetString("ReceiveBtcArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Ether ↓.
        /// </summary>
        internal static string ReceiveEther {
            get {
                return ResourceManager.GetString("ReceiveEther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Token ↓.
        /// </summary>
        internal static string ReceiveToken {
            get {
                return ResourceManager.GetString("ReceiveToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Coins.
        /// </summary>
        internal static string SelectCoins {
            get {
                return ResourceManager.GetString("SelectCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send BTC.
        /// </summary>
        internal static string SendBtc {
            get {
                return ResourceManager.GetString("SendBtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send BTC ↑.
        /// </summary>
        internal static string SendBtcArrow {
            get {
                return ResourceManager.GetString("SendBtcArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send ERC20.
        /// </summary>
        internal static string SendERC20 {
            get {
                return ResourceManager.GetString("SendERC20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send ETH.
        /// </summary>
        internal static string SendEth {
            get {
                return ResourceManager.GetString("SendEth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Ethers ↑.
        /// </summary>
        internal static string SendEthers {
            get {
                return ResourceManager.GetString("SendEthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Token ↑.
        /// </summary>
        internal static string SendToken {
            get {
                return ResourceManager.GetString("SendToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Your Address.
        /// </summary>
        internal static string ShareYourAddress {
            get {
                return ResourceManager.GetString("ShareYourAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Address and Amount.
        /// </summary>
        internal static string SpecifyAddressAndAmount {
            get {
                return ResourceManager.GetString("SpecifyAddressAndAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nftPage.
        /// </summary>
        internal static string SSnftPage {
            get {
                return ResourceManager.GetString("SSnftPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tokensPages.
        /// </summary>
        internal static string SStokensPages {
            get {
                return ResourceManager.GetString("SStokensPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token ID.
        /// </summary>
        internal static string TokenId {
            get {
                return ResourceManager.GetString("TokenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Fee.
        /// </summary>
        internal static string TotalFee {
            get {
                return ResourceManager.GetString("TotalFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is successfully broadcasted, your Transaction ID:.
        /// </summary>
        internal static string TransactionBroadcastedMsg {
            get {
                return ResourceManager.GetString("TransactionBroadcastedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Details.
        /// </summary>
        internal static string TransactionDetails {
            get {
                return ResourceManager.GetString("TransactionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Id.
        /// </summary>
        internal static string TransactionId {
            get {
                return ResourceManager.GetString("TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your transaction is being processed. It can take couple of minutes, please wait..
        /// </summary>
        internal static string TransactionIsBeingProcessedMsg {
            get {
                return ResourceManager.GetString("TransactionIsBeingProcessedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions History.
        /// </summary>
        internal static string TransactionsHistory {
            get {
                return ResourceManager.GetString("TransactionsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions not Found. .
        /// </summary>
        internal static string TransactionsNotFoundMsg {
            get {
                return ResourceManager.GetString("TransactionsNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITS.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspent Transactions.
        /// </summary>
        internal static string UnspentTransactions {
            get {
                return ResourceManager.GetString("UnspentTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are updating your wallet, this adress might be already used, please wait.
        /// </summary>
        internal static string UpdatingWalletMsg {
            get {
                return ResourceManager.GetString("UpdatingWalletMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTXO&apos;s not Found.
        /// </summary>
        internal static string UtxosNotFound {
            get {
                return ResourceManager.GetString("UtxosNotFound", resourceCulture);
            }
        }
    }
}
